# Terra Oldham's Website
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Software Engineer
email: terraoldham@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Think like a proton and be positive. @HearsaySocial Superhero | @SantaClaraUniv Engineer | PNW Transplant
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://terraoldham.github.io" # the base hostname & protocol for your site
twitter_username: terradactyle
github_username:  terraoldham

# Build settings
markdown: kramdown
